global:
  scrape_interval:     15s

scrape_configs:
  - job_name: 'apache-exporter'
    static_configs:
      - targets: ['apache-exporter:9117']
  - job_name: 'ejbWithVaadin-exporter'
    static_configs:
      - targets: ['host.docker.internal:7001']
    metrics_path: /WeblogicVaadinGridExampleSpring/metrics
